sudo: required
services:
    - docker

before_install:
    - docker build -t arthurrfanti/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true arthurrfanti/docker-react npm run test

